name: Variables
pname: variables
description: Flow variables management
version: 0.1.1
icon: code
private: false
base: true
category: base_flow_management
python:
  - '3.9'
  - '3.10'
  - '3.11'
  - '3.12'
